import Vue from "vue";
import {
    Button,
    ColorPicker,
    Cascader,
    Container,
    Dropdown,
    DropdownItem,
    DropdownMenu,
    Dialog,
    Form,
    FormItem,
    Header,
    Input,
    MessageBox,
    Main,
    Menu,
    MenuItem,
    Slider,
    Option,
    Select,
    Table,
    TableColumn,
    Tree,
    Upload,
    Pagination,
} from "element-ui";
Vue.use(Input);
Vue.use(Dropdown);
Vue.use(DropdownItem);
Vue.use(DropdownMenu);
Vue.use(Dialog);
Vue.use(Form);
Vue.use(FormItem);
Vue.use(ColorPicker);
Vue.use(Slider);
Vue.use(Cascader);
Vue.use(Table);
Vue.use(TableColumn);
Vue.use(Select);
Vue.use(Button);
Vue.use(Option);
Vue.use(Upload);
Vue.use(Header);
Vue.use(Main);
Vue.use(Menu);
Vue.use(MenuItem);
Vue.use(Container);
Vue.use(Tree);
Vue.use(Pagination);
export { MessageBox }